name: Build Project to Ensure Compilation

on:
  schedule:
    # Runs every 2 days at midnight (UTC)
    - cron: '0 0 */2 * *'
  
  pull_request:
    branches: [ "main" ]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0'
      
      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build the project
        run: dotnet build --configuration Release

    # For unit tests when they are made
    # - name: Run tests
    #   run: dotnet test --configuration Release
